name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build all apps
        run: yarn build

      # ▸ Deploy Web App to Netlify
      # - name: Deploy Web App to Netlify
      #   run: |
      #     npx netlify deploy --prod --cwd=apps/web --site=$NETLIFY_SITE_ID_WEB --auth=$NETLIFY_AUTH_TOKEN
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID_WEB: ${{ secrets.NETLIFY_SITE_ID_WEB }}

      # ▸ Deploy Docs App to Netlify
      # - name: Deploy Docs App to Netlify
      #   run: |
      #     npx netlify deploy --prod --cwd=apps/docs --site=$NETLIFY_SITE_ID_DOCS --auth=$NETLIFY_AUTH_TOKEN
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID_DOCS: ${{ secrets.NETLIFY_SITE_ID_DOCS }}

      - name: Trigger Render Deploy
        run: curl -X POST $RENDER_DEPLOY_HOOK_URL
