name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build all apps
        run: yarn build

      - name: Deploy Web App to Netlify
        run: >
          npx netlify deploy
          --prod
          --cwd=apps/web
          --site=$NETLIFY_SITE_ID_WEB
          --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID_WEB: ${{ secrets.NETLIFY_SITE_ID_WEB }}

      - name: Deploy Docs App to Netlify
        run: >
          npx netlify deploy
          --prod
          --cwd=apps/docs
          --site=$NETLIFY_SITE_ID_DOCS
          --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID_DOCS: ${{ secrets.NETLIFY_SITE_ID_DOCS }}

      # - name: Deploy Landing API to Railway
      #   uses: bervProject/railway-deploy@main
      #   with:
      #     project: ${{ secrets.RAILWAY_PROJECT_ID }}
      #     service: landing-api
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
