name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SVC_ID: dffb6765-1283-4c94-b854-dba988145254
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build all apps
        run: yarn build

      # ▸ Deploy Web App to Netlify
      # - name: Deploy Web App to Netlify
      #   run: |
      #     npx netlify deploy --prod --cwd=apps/web --site=$NETLIFY_SITE_ID_WEB --auth=$NETLIFY_AUTH_TOKEN
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID_WEB: ${{ secrets.NETLIFY_SITE_ID_WEB }}

      # ▸ Deploy Docs App to Netlify
      # - name: Deploy Docs App to Netlify
      #   run: |
      #     npx netlify deploy --prod --cwd=apps/docs --site=$NETLIFY_SITE_ID_DOCS --auth=$NETLIFY_AUTH_TOKEN
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID_DOCS: ${{ secrets.NETLIFY_SITE_ID_DOCS }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Test API to Railway
        run: |
          cd apps/test-api
          railway up --service=$SVC_ID
